Repository sequentech/voting-booth, pull requests merged in 2023-09, with the labels that each got.

#378 🐞 pop up election-id to long
  avBooth/booth-directive/booth-directive.less
Labels: bug

#379 🐞 pop up election-id to long
  avBooth/booth-directive/booth-directive.less
Labels: bug

#380 Security updates
  index.html
  package.json
  yarn.lock
Labels: dependencies

#383 🐞 child election with bigger title in election chooser (#382)
  avBooth/booth-children-elections-directive/booth-children-elections-directive.less
Labels: bug

#384 🐞 Accordion doesn't work as is-js is not loaded
  app.js
  avBooth/accordion-option-directive/accordion-option-directive.js
  avBooth/is-service.js
  avBooth/selected-options-directive/selected-options-directive.js
  index.html
Labels: bug

#386 ✨ Write-ins multiple fields (#350)
  avBooth/error-checker-generator-service.js
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
  locales/ca.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/gl.json
  locales/sv.json
Labels: enhancement

#387 ✨ Add html support for write-in extrafield labels/help
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Labels: enhancement

#388 ✨ Visualization of write-in fields in Review (#363)
  avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
  avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Labels: enhancement

#392 Add italian language support
  Gruntfile.js
  locales/it.json
Labels: enhancement

#391 ✨ Voting-booth: Improve election info in the ballot ticket PDF for parent-children elections
  avBooth/success-screen-directive/success-screen-directive.js
Labels: enhancement

#393 🐞disable election chooser option is not working
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Labels: bug

#394 🐞disable election chooser option is not working (#393)
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Labels: bug
