Repository sequentech/voting-booth, pull requests merged in 2023-06, with the labels that each got.

#328 Bump socket.io-parser from 4.0.4 to 4.2.3
  package.json
  yarn.lock
Labels: dependencies

#329 Bump socket.io-parser from 4.0.4 to 4.2.3 (#328)
  package.json
  yarn.lock
Labels: dependencies

#331 🐞 Fix pixelated logo
  img/Sequent_logo.svg
Labels: bug

#332 ✨ Shrink header/footer by default (#330)
  avBooth/booth-directive/booth-directive.less
Labels: enhancement

#333 🐞 Fix pixelated logo (#331)
  img/Sequent_logo.svg
Labels: bug

#335 🐞French translation is tagged as English
  locales/ca.json
  locales/es.json
  locales/gl.json
Labels: bug

#339 🐞French translation is tagged as English (#335)
  locales/ca.json
  locales/es.json
  locales/gl.json
Labels: bug

#336 ✨dynamic position of invalid vote option
  avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Labels: enhancement

#340 ✨dynamic position of invalid vote option (#336)
  avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Labels: enhancement

#334 ✨ Countdown until logout
  SequentConfig.js
  avBooth/booth-directive/booth-directive.js
  locales/ca.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/gl.json
  locales/sv.json
Labels: enhancement, breaking-change

#338 `master` branch should be using `master` version number and not `8.0.0`
  Gruntfile.js
  SequentConfig.js
  index.html
  package.json
Labels: bug

#342 Visual highlighting of ballot sheet zone
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
  avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.less
  locales/en.json
Labels: enhancement, breaking-change

#341 ✨different responses on timeout in voting booth
  avBooth/booth-directive/booth-directive.js
  avBooth/casting-ballot-screen-directive/casting-ballot-screen-directive.js
  avBooth/casting-ballot-screen-directive/casting-ballot-screen-directive.less
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
  avBooth/error-screen-directive/error-screen-directive.html
  avBooth/error-screen-directive/error-screen-directive.js
  avBooth/error-screen-directive/error-screen-directive.less
  avBooth/success-screen-directive/success-screen-directive.js
  crypto/cast-ballot-service.js
  img/error.png
  locales/ca.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/gl.json
  locales/sv.json
Labels: enhancement

#343 Security updates: word-wrap resolution
  package.json
  yarn.lock
Labels: dependencies

#344 Security updates: word-wrap resolution (#343)
  package.json
  yarn.lock
Labels: dependencies

#345 Security updates: word-wrap resolution (#343)
  package.json
  yarn.lock
Labels: dependencies
