Repository sequentech/voting-booth, pull requests merged in 2023-02, with the labels that each got.

#296 Fix tab/accessibility issues
  avBooth/booth-directive/booth-directive.js
  avBooth/booth-header-directive/booth-header-directive.html
  avBooth/booth.less
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
  avBooth/invalid-answers-controller/invalid-answers-controller.html
  avBooth/pairwise-beta-directive/pairwise-beta-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.js
  avBooth/review-ballot-directive/review-ballot-directive.less
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
  avBooth/success-screen-directive/success-screen-directive.html
  locales/en.json
  locales/es.json
Labels: bug

#300 Accessibility fixes for accordion layout
  avBooth/accordion-option-directive/accordion-option-directive.less
  avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
  avBooth/multi-question-directive/multi-question-directive.html
  avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
Labels: bug

#302 Fix accessibility issues
  avBooth/accordion-option-directive/accordion-option-directive.less
  avBooth/booth-directive/booth-directive.js
  avBooth/booth-header-directive/booth-header-directive.html
  avBooth/booth.less
  avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
  avBooth/invalid-answers-controller/invalid-answers-controller.html
  avBooth/multi-question-directive/multi-question-directive.html
  avBooth/pairwise-beta-directive/pairwise-beta-directive.html
  avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.js
  avBooth/review-ballot-directive/review-ballot-directive.less
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
  avBooth/success-screen-directive/success-screen-directive.html
  locales/en.json
  locales/es.json
Labels: bug

#282 adding extended support for rigid, open and loosely bound lists
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.js
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
Labels: enhancement, breaking-change

#303 Adding extended support for rigid, open and loosely bound lists
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.js
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
Labels: enhancement, breaking-change

#299 Warn implicit and explicit votes fix
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
Labels: bug

#305 Add support for warn-invalid-implicit-and-explicit (#298)
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
  locales/en.json
  locales/es.json
Labels: enhancement

#306 Warn implicit and explicit votes fix (#299)
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
Labels: bug
