Repository sequentech/voting-booth, pull requests merged in 2023-01, with the labels that each got.

#290 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#291 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#284 Live preview
  app.js
  avBooth/booth-directive/booth-directive.js
  avBooth/booth-header-directive/booth-header-directive.html
  avBooth/booth.html
  avBooth/booth.js
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
  locales/en.json
  locales/es.json
Labels: enhancement

#292 Live preview (#284)
  app.js
  avBooth/booth-directive/booth-directive.js
  avBooth/booth-header-directive/booth-header-directive.html
  avBooth/booth.html
  avBooth/booth.js
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
  locales/en.json
  locales/es.json
Labels: enhancement

#293 Fx tab/accessibility issues
  avBooth/booth-directive/booth-directive.js
  avBooth/booth-header-directive/booth-header-directive.html
  avBooth/booth.less
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
  avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
  avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
  avBooth/invalid-answers-controller/invalid-answers-controller.html
  avBooth/pairwise-beta-directive/pairwise-beta-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.html
  avBooth/review-ballot-directive/review-ballot-directive.js
  avBooth/review-ballot-directive/review-ballot-directive.less
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
  avBooth/success-screen-directive/success-screen-directive.html
  locales/en.json
  locales/es.json
Labels: bug

#297 Fix label warnings
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
  avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
Labels: bug

#298 Add support for warn-invalid-implicit-and-explicit
  avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
  locales/en.json
  locales/es.json
Labels: enhancement
