Repository sequentech/voting-booth, pull requests merged in 2024-04, with the labels that each got.

#436 🐞 Invalid vote policy
  avBooth/booth-directive/booth-directive.js
  avBooth/error-checker-generator-service.js
Labels: bug, enhancement

#437 🐞 Invalid vote policy (#436)
  avBooth/booth-directive/booth-directive.js
  avBooth/error-checker-generator-service.js
Labels: bug, enhancement

#439 🐞 Warning characters rendered incorrectly in review screen (#438)
  avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
  avBooth/review-ballot-v2-directive/review-ballot-v2-directive.js
Labels: bug

#440 🛡 Security updates
  package.json
  yarn.lock
Labels: dependencies
